### ISSUE TITLE
centos7 下编译后toluapp命令出错

### ISSUE THREAD

**Issue by oneStarCai** [ToyAuthor/luapp#1]
toluapp -o lua_tclass.c tclass.pkg

** tolua internal error: [string "tolua embedded: src/bin/lua/package.lua"]:325: attempt to call a nil value (field 'gfind').

stack traceback:
	[string "tolua: embedded Lua code 23"]:5: in main chunk

已经把src/bin/lua/package.lua 里边的gfind改成了gmatch了，我用的lua版本是5.3的

**Comment by ToyAuthor** [comment]
luapp ≠ tolua++
https://github.com/LuaDist/toluapp
