### ISSUE TITLE
bool Table::isExist(T key) , is the return value invalid?

### ISSUE THREAD

**Issue by BigPig0** [ToyAuthor/luapp#2]
`if ( it == _mapInt.end() )
{
	return true;
}
return false;`
should be 
`if ( it == _mapInt.end() )
{
	return false;
}
return true;`
?

**Comment by ToyAuthor** [comment]
Oh! That is a big mistake.
Thank you.

**Comment by ToyAuthor** [comment]
Fixed at v2.4.1
